Fix memory leak: https://github.com/robotframework/RIDE/issues/1868
robotframework/RIDE pull request #2276
Opened 2020-08-17 10:07 UTC by jnhyperion

https://github.com/robotframework/RIDE/issues/1868

2020-08-17 10:08 UTC, jnhyperion commented
https://github.com/robotframework/RIDE/issues/1868

2020-08-17 18:54 UTC, HelioGuilherme66 commented
@jnhyperion @Nyral With this PR, the Grid Editor will show the About content (which used to be temporary). Whenever a user opens a file, they must select an item on Tree. This may be an additional step, and is a noticeable change. Don't you think we should have this configurable?

2020-08-18 01:44 UTC, jnhyperion commented
Or we can make some more changes to prevent tree nodes will be created twice when reloading workspace, this is only a minimum and "lazy" fix. what do you think?

2020-08-18 09:09 UTC, HelioGuilherme66 commented
Yes, I would prefer to keep root node selected. Why are they being duplicated?

2020-08-18 09:33 UTC, jnhyperion commented
it's because message RideDataFileSet is published right after tree nodes are created, and the root node is selected, then the message handlers remove all the nodes and recreate new nodes. this behaviour causes memory leak. I don't know why, maybe it's a wxpython bug, but unfortunately I cannot manage to prove it.

2020-08-24 06:01 UTC, jnhyperion commented on utest/ui/test_tree.py
> +        assert_equal(self._get_selected_label(), '')
reverted

2020-08-24 22:15 UTC, HelioGuilherme66 requested changes
Did you forgot to push the changes?

2020-08-24 22:15 UTC, HelioGuilherme66 commented on src/robotide/ui/mainframe.py
> +        import objgraph
This does not look like essential code.

2020-08-25 02:51 UTC, jnhyperion commented on src/robotide/ui/mainframe.py
> +        import objgraph
already reverted this part, see https://github.com/robotframework/RIDE/pull/2276/files "File Changed" directly.

2020-08-25 09:16 UTC, HelioGuilherme66 approved these changes

2020-08-25 09:17 UTC, merged