Add CONTRIBUTIONS.adoc
robotframework/RIDE pull request #2493
Opened 2022-10-01 10:01 UTC by sofezticated-gentleman

here, I have created a `.adoc` file called `CONTRIBUTIONS.adoc`  it contains some contribution guidelines. IF there's any errors or possible imporovements please suggest so

2022-10-01 10:05 UTC, sofezticated-gentleman commented
@HelioGuilherme66 , I have creted a `CONTRIBUTIONS.adoc` file if there are any issues or changes you would like to see please tell me

2022-10-01 11:14 UTC, HelioGuilherme66 commented on CONTRIBUTIONS.adoc
> +code must support both Python 2 and Python 3.
>must support both Python 2 and Python 3.
must support Python 3 (actually, greater than 3.6). RIDE's code still have some Python 2 conditioning, due to its dual compatibility on version 1.7.4.2, and also in the included Robot Framework library from version 3.1.2.

2022-10-01 11:50 UTC, HelioGuilherme66 requested changes
Overall this is what we needed. Good job!

We need to remove specific parts of Robot Framework, and replace with RIDE ones.

You should add a special reference to wxPython, near the coding section. For example:

RIDE graphical user interface, can only exist due the use of wxPython (from wxWidgets). Users wanting to write Python code for RIDE, should be acquainted with https://wxpython.org[wxPython] in particular by exploring its demo.

2022-10-01 11:50 UTC, HelioGuilherme66 commented on CONTRIBUTIONS.adoc
> +is 88 characters. This is also what
>is 88 characters. This is also what

is 100 characters. The recommended size of 88 characters, is what

2022-10-01 11:50 UTC, HelioGuilherme66 commented on CONTRIBUTIONS.adoc
> +With Robot Framework tests the maximum line length is 100.
>With Robot Framework tests the maximum line length is 100.

[Remove this line]

2022-10-01 11:50 UTC, HelioGuilherme66 commented on CONTRIBUTIONS.adoc
> +==== User Guide
>==== User Guide

==== Robot Framework's User Guide

2022-10-01 11:50 UTC, HelioGuilherme66 commented on CONTRIBUTIONS.adoc
> +
=== RIDE's Wiki

https://github.com/robotframework/RIDE/wiki[RIDE's Wiki] is the preferred location for the documentation. This is to promote collaboration from users, and hopefully, to have the content easily updated.

2022-10-01 11:50 UTC, HelioGuilherme66 commented on CONTRIBUTIONS.adoc
> +==== Libraries
This section must be properly adjusted to RIDE:
- we don't provide Libraries
- important to know how to run unit tests
- important to know how to run RIDE (with invoke)
- important to know how to run RIDE using the debug option

2022-10-01 11:50 UTC, HelioGuilherme66 commented on CONTRIBUTIONS.adoc
> +https://groups.google.com/forum/#!forum/robotframework-users[robotframework-users]
Add the preferred Forum (like in README: https://forum.robotframework.org/c/tools/ride/21)

2022-10-01 11:50 UTC, HelioGuilherme66 commented on CONTRIBUTIONS.adoc
> +implementing, you can first ask on link:[robotframework-users] mailing
(again add the Forum as first medium)

2022-10-01 11:50 UTC, HelioGuilherme66 commented on CONTRIBUTIONS.adoc
> +http://webchat.freenode.net/?channels=robotframework&prompt=1[IRC]
This IRC is rarely used, so it is better to remove.

2022-10-01 11:50 UTC, HelioGuilherme66 commented on CONTRIBUTIONS.adoc
> +https://robotframework-slack-invite.herokuapp.com[Slack]. These and
Important to mention the **#ride** channel.

2022-10-01 11:50 UTC, HelioGuilherme66 commented on CONTRIBUTIONS.adoc
> +* Robot Framework version
* RIDE version

2022-10-01 11:50 UTC, HelioGuilherme66 commented on CONTRIBUTIONS.adoc
> +Robot Framework uses the general Python code conventions defined in
RIDE

or

Robot Framework and RIDE

2022-10-01 12:06 UTC, HelioGuilherme66 commented
Please rename the file to `CONTRIBUTING.adoc` (this is the standard name).

2022-10-02 07:28 UTC, sofezticated-gentleman commented
okay @HelioGuilherme66  I will do the required changes and make a pr by today itself

2022-10-02 09:26 UTC, HelioGuilherme66 commented
> will do the required changes and make a pr by today itself

@sofezticated-gentleman No need for PR, you just have to make the changes, commit and push to your branch. This PR will be auto-updated.

2022-10-02 13:40 UTC, sofezticated-gentleman commented
@HelioGuilherme66 is this link still relevant : https://www.tutorialspoint.com/robot_framework/robot_framework_first_test_case_using_ride.htm and this too : https://www.softwaretestinghelp.com/getting-started-with-robot-framework-ride/

2022-10-03 06:17 UTC, sofezticated-gentleman commented
> Please rename the file to `CONTRIBUTING.adoc` (this is the standard name).

okay

2022-10-04 16:37 UTC, sofezticated-gentleman commented
@HelioGuilherme66 @JFoederer please review the pr

2022-10-10 22:02 UTC, HelioGuilherme66 approved these changes
Will improve the content by using links to other documents, in future releases.

2022-10-11 07:08 UTC, sofezticated-gentleman commented
Hey @HelioGuilherme66 can you please accept it as a hacktober fest issue?

2022-10-11 16:19 UTC, sofezticated-gentleman commented
@HelioGuilherme66 are there any issues or ways i can contribute! i have basic ml knowledge and im comfortable python and its libs?

2022-10-12 17:24 UTC, HelioGuilherme66 commented
@sofezticated-gentleman Are you able to use Slack? We should not be communicating here.

2022-10-30 00:14 UTC, merged